### ISSUE TITLE
华为荣耀20pro 设置Header导致崩溃问题

### ISSUE THREAD

**Issue by GoodmanLi** [scwang90/SmartRefreshLayout#1047]
**详细描述**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用版本**
```gradle
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.5.1'
```
**使用代码**
```java
        mRefresh.setRefreshHeader(new DeliveryHeader(getContext()));
```

**布局代码**
```xml
    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/refresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlHeaderHeight="200dp">
    <android.support.v7.widget.RecyclerView
        android:id="@+id/rv_earning"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

    </android.support.v7.widget.RecyclerView>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>
```

**报错日志**
```
2019-10-14 11:25:28.346 4094-4094/com.gte E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gte, PID: 4094
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1252)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1219)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1169)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1130)
        at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.createCachedBitmapIfNeeded(PathsDrawable.java:216)
        at com.scwang.smartrefresh.layout.internal.pathview.PathsDrawable.draw(PathsDrawable.java:128)
        at com.scwang.smartrefresh.header.DeliveryHeader.onDraw(DeliveryHeader.java:159)
        at android.view.View.draw(View.java:20495)
        at android.view.View.updateDisplayListIfDirty(View.java:19306)
        at android.view.View.draw(View.java:20223)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:838)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
        at android.view.View.updateDisplayListIfDirty(View.java:19297)
```

**问题重现**
问题重现崩溃:
1. 设置Header
2.下拉刷新

并不是所有的header都会崩溃，我试过有DropBoxHeader和MaterialHeader不会崩溃

**预期行为**
修复bug

**屏幕截图**
无

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为荣耀20pro]
 - Android版本: [e.g. Android 9.0]
 - 设备型号 [YAL-AL10]
 - 系统版本（Magic 2.1.0）

**附加信息**
[报错日志.txt](https://github.com/scwang90/SmartRefreshLayout/files/3722846/default.txt)

并不是所有的header都会崩溃，我试过有DropBoxHeader和MaterialHeader不会崩溃

**Comment by scwang90** [comment]
老版本确实存在这个问题
