### ISSUE TITLE
遇到空指针

### ISSUE THREAD

**Issue by yuSun90** [scwang90/SmartRefreshLayout#1099]
0
java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smartrefresh.layout.constant.SpinnerStyle com.scwang.smartrefresh.layout.a.h.getSpinnerStyle()' on a null object reference
1
at com.scwang.smartrefresh.layout.SmartRefreshLayout$RefreshKernelImpl.moveSpinner(SmartRefreshLayout.java:3043)
2
at com.scwang.smartrefresh.layout.SmartRefreshLayout$10$1.onAnimationUpdate(SmartRefreshLayout.java:2648)
3
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
4
at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384)
5
at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427)
6
at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759)
7
at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
8
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
9
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
10
at android.view.Choreographer.doFrame(Choreographer.java:603)
11
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
12
at android.os.Handler.handleCallback(Handler.java:739)
13
at android.os.Handler.dispatchMessage(Handler.java:95)
14
at android.os.Looper.loop(Looper.java:148)
15
at android.app.ActivityThread.main(ActivityThread.java:5417)
16
at java.lang.reflect.Method.invoke(Method.java)
17
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
18
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by scwang90** [comment]
需要告知使用的版本

**Comment by scwang90** [comment]
也可以更换到最新版本

**Comment by yuSun90** [comment]
版本号是 1.1.0-alpha-7

**Comment by scwang90** [comment]
切换到最新版本就好了
