### ISSUE TITLE
添加到布局后运行报错

### ISSUE THREAD

**Issue by renkchina** [scwang90/SmartRefreshLayout#110]
java.lang.NoSuchMethodError: No static method com_scwang_smartrefresh_layout_SmartRefreshLayout$$Lambda$15_lambda$static$1(Landroid/content/Context;Lcom/scwang/smartrefresh/layout/api/RefreshLayout;)Lcom/scwang/smartrefresh/layout/api/RefreshHeader; in class Lcom/scwang/smartrefresh/layout/SmartRefreshLayout; or its super classes (declaration of 'com.scwang.smartrefresh.layout.SmartRefreshLayout' appears in /data/app/bag.small-2/base.apk)
at com.scwang.smartrefresh.layout.SmartRefreshLayout$$Lambda$15.createRefreshHeader(Unknown Source)at com.scwang.smartrefresh.layout.SmartRefreshLayout.onAttachedToWindow(SmartRefreshLayout.java:383)

**Comment by scwang90** [comment]
请使用最新版本
