### ISSUE TITLE
gradle-6.1.1 版本下xml无法预览布局，错误信息如下

### ISSUE THREAD

**Issue by loperSeven** [scwang90/SmartRefreshLayout#1248]
gradle-6.1.1 版本下xml无法预览布局，错误信息如下
```kotlin
java.lang.NoClassDefFoundError: androidx/legacy/widget/Space
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate_Original(SmartRefreshLayout.java:352)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate(SmartRefreshLayout.java)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1136)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1126)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:501)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:348)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:404)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:678)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$8(RenderTask.java:809)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: androidx.legacy.widget.Space
	at com.android.tools.idea.rendering.classloading.RenderClassLoader.loadClassFromNonProjectDependency(RenderClassLoader.java:123)
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:153)
	at com.android.tools.idea.rendering.classloading.RenderClassLoader.findClass(RenderClassLoader.java:78)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:187)
	... 21 more

```

**Comment by eco-ryoma** [comment]
我也遇到了，也是gradle-6.1.1  xml 不能预览， 但我看有的项目gradle-6.1.1  xml布局又预览正常，所以感觉跟这个gradle版本没什么直接相关，暂时还没找到原因；
现在每次都是先注释掉SmartRefreshLayout标签 xml中它所包含的部分才能正常预览 @chengzhijun0706 @scwang90
