### ISSUE TITLE
崩溃 android.widget.LinearLayout cannot be cast to android.widget.ImageView

### ISSUE THREAD

**Issue by petterEat** [scwang90/SmartRefreshLayout#1303]
2021-01-28 09:39:23.225 23092-23092/com.chinascrm.mystore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chinascrm.mystore, PID: 23092
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chinascrm.mystore/com.chinascrm.mystore.function.MainAct}: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chinascrm.mystore/com.chinascrm.mystore.function.MerchantNewAct}: android.view.InflateException: Binary XML file line #47: Binary XML file line #47: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2976)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
     Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chinascrm.mystore/com.chinascrm.mystore.function.MerchantNewAct}: android.view.InflateException: Binary XML file line #47: Binary XML file line #47: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2976)
        at android.app.ActivityThread.startActivityNow(ActivityThread.java:2786)
        at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:139)
        at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:366)
        at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:774)
        at android.widget.TabHost.setCurrentTab(TabHost.java:428)
        at android.widget.TabHost.addTab(TabHost.java:238)
        at com.chinascrm.mystore.function.MainAct.onCreate(MainAct.java:57)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922) 
     Caused by: android.view.InflateException: Binary XML file line #47: Binary XML file line #47: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
     Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:884)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:845)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:887)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:845)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.chinascrm.mystore.BaseActivity.onCreate(BaseActivity.kt:27)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
2021-01-28 09:39:23.228 23092-23092/com.chinascrm.mystore E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
        at android.app.ActivityThread.startActivityNow(ActivityThread.java:2786)
        at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:139)
        at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:366)
        at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:774)
        at android.widget.TabHost.setCurrentTab(TabHost.java:428)
        at android.widget.TabHost.addTab(TabHost.java:238)
        at com.chinascrm.mystore.function.MainAct.onCreate(MainAct.java:57)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
     Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ImageView
        at com.scwang.smartrefresh.layout.header.ClassicsHeader.<init>(ClassicsHeader.java:85)
        	... 39 more

**Comment by petterEat** [comment]
This report error appears rarely, but flashes away as soon as it appears

**Comment by petterEat** [comment]
1.1.2
