### ISSUE TITLE
没有单独androidx的版本吗，现在的类都引用support包，会引发编译问题

### ISSUE THREAD

**Issue by li-xiaojun** [scwang90/SmartRefreshLayout#1338]
没有单独androidx的版本吗，现在的类都引用support包，在特定情况会引发编译问题。
直接使用类库是没问题的，因为gradle会处理，但是我的库引用了SmartRefresh后，我的类全部是androidx的。这个时候用我的库就会出现问题，gradle的androidx处理无法嵌套多层类库，希望修改下：
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.seallive.app, PID: 21033
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/NestedScrollingParent;
        at com.seallive.app.App.onCreate(App.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7387)
        at android.app.ActivityThread.access$2400(ActivityThread.java:251)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2280)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by woitaylor** [comment]
说了要把那两行加上
