### ISSUE TITLE
NullPointerException For TwoLevelHeader.java line 211

### ISSUE THREAD

**Issue by Piashsarker** [scwang90/SmartRefreshLayout#1388]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smart.refresh.layout.a.e com.scwang.smart.refresh.layout.a.e.a(com.scwang.smart.refresh.layout.constant.RefreshState)' on a null object reference
       at com.scwang.smart.refresh.header.TwoLevelHeader.onMoving(TwoLevelHeader.java:211)
       at com.scwang.smart.refresh.layout.SmartRefreshLayout$RefreshKernelImpl.moveSpinner(SmartRefreshLayout.java:3828)
       at com.scwang.smart.refresh.layout.SmartRefreshLayout$8$1.onAnimationUpdate(SmartRefreshLayout.java:3347)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by scwang90** [comment]
问题已修复
