### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal pattern character 't'

### ISSUE THREAD

**Issue by kimiangel** [scwang90/SmartRefreshLayout#1431]
java.lang.IllegalArgumentException: Illegal pattern character 't'
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:934)
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:720)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:691)
        at com.scwang.smart.refresh.header.ClassicsHeader.<init>(ClassicsHeader.java:205)
        at com.scwang.smart.refresh.header.ClassicsHeader.<init>(ClassicsHeader.java:76)

当手机设置成英语的时候，初始化就会报错

**Comment by 1119093254** [comment]
ClassicsHeader.REFRESH_HEADER_UPDATE ="'Last update' M-d HH:mm"
