### ISSUE TITLE
Crash when SmartRefreshLayout draw child

### ISSUE THREAD

**Issue by foxcode7** [scwang90/SmartRefreshLayout#1445]
`
java.lang.ArrayIndexOutOfBoundsException: length=73; index=-6
	at android.text.StaticLayout.getLineTop(StaticLayout.java:1213)
	at android.widget.TextView.getExtendedPaddingTop(TextView.java:2691)
	at android.widget.TextView.onDraw(TextView.java:7957)
	at android.view.View.draw(View.java:21612)
	at android.view.View.updateDisplayListIfDirty(View.java:20481)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21615)
	at android.view.View.updateDisplayListIfDirty(View.java:20481)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:830)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21615)
	at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
	at android.view.View.updateDisplayListIfDirty(View.java:20481)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.updateDisplayListIfDirty(View.java:20472)
	at android.view.View.draw(View.java:21341)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4417)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4177)
	at android.view.View.draw(View.java:21615)
	at com.android.internal.policy.DecorView.draw(DecorView.java:844)
	at android.view.View.updateDisplayListIfDirty(View.java:20481)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3735)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3530)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2867)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1820)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**Comment by Khaos116** [comment]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=101; index=-25
       at android.widget.Scroller.computeScrollOffset(Scroller.java:337)
       at com.scwang.smart.refresh.layout.SmartRefreshLayout.computeScroll(SmartRefreshLayout.java:847)
       at android.view.View.updateDisplayListIfDirty(View.java:22295)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.draw(View.java:23484)
       at android.view.View.updateDisplayListIfDirty(View.java:22312)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.draw(View.java:23484)
       at android.view.View.updateDisplayListIfDirty(View.java:22312)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.draw(View.java:23484)
       at android.view.View.updateDisplayListIfDirty(View.java:22312)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.updateDisplayListIfDirty(View.java:22303)
       at android.view.View.draw(View.java:23189)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4615)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4368)
       at android.view.View.draw(View.java:23484)
       at com.android.internal.policy.DecorView.draw(DecorView.java:903)
       at android.view.View.updateDisplayListIfDirty(View.java:22312)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4970)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4665)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3823)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9560)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1414)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1422)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1049)
       at android.view.Choreographer.doFrame(Choreographer.java:937)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1397)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8423)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
