### ISSUE TITLE
崩溃日志

### ISSUE THREAD

**Issue by liguangze** [scwang90/SmartRefreshLayout#1516]
来回快速下拉，就会报错
   java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:927)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4002)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
        at android.view.View.dispatchPointerEvent(View.java:13689)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5497)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5300)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4803)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4856)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4822)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4830)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5019)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4803)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4856)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4822)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4830)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4803)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7520)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7489)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7450)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7645)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7596)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7669)

**Comment by scwang90** [comment]
老版本已经不再维护，请切换新版本
