### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by bravetou** [scwang90/SmartRefreshLayout#1584]
java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smart.refresh.layout.api.RefreshKernel com.scwang.smart.refresh.layout.api.RefreshKernel.onAutoRefreshAnimationEnd(android.animation.Animator, boolean)' on a null object reference
                                         	at com.scwang.smart.refresh.header.MaterialHeader$1.onAnimationEnd(MaterialHeader.java:397)
                                         	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1112)
                                         	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:584)
                                         	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1257)
                                         	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1516)
                                         	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:272)
                                         	at android.animation.AnimationHandler.access$100(AnimationHandler.java:39)
                                         	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:79)
                                         	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1597)
                                         	at android.view.Choreographer.doCallbacks(Choreographer.java:1263)
                                         	at android.view.Choreographer.lambda$new$0$Choreographer(Choreographer.java:281)
                                         	at android.view.Choreographer$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                         	at android.os.Handler.handleCallback(Handler.java:966)
                                         	at android.os.Handler.dispatchMessage(Handler.java:110)
                                         	at android.os.Looper.loopOnce(Looper.java:205)
                                         	at android.os.Looper.loop(Looper.java:293)
                                         	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
                                         	at android.app.ActivityThread.main(ActivityThread.java:9975)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

**Comment by bravetou** [comment]
版本2.1.0

**Comment by mobilewhj** [comment]
我也遇见了额，尤其是频繁的前后台切换，后者在后台久了再回到前台都能出现这个问题。不知道怎么办。

**Comment by wangjintao** [comment]
我也是，又退回2.0.5了

**Comment by stevenwsg** [comment]
Attempt to invoke interface method 'com.scwang.smart.refresh.layout.api.RefreshKernel com.scwang.smart.refresh.layout.api.RefreshKernel.onAutoRefreshAnimationEnd

我也遇到了
