### ISSUE TITLE
抱歉作者大佬， 我发现2.1.1还是有空指针问题

### ISSUE THREAD

**Issue by stevenwsg** [scwang90/SmartRefreshLayout#1589]
2024-12-27 20:02:51.263  2083-2083  AndroidRuntime          com.cn21.cloudeyes.pro               E  FATAL EXCEPTION: main
                                                                                                    Process: com.cn21.cloudeyes.pro, PID: 2083
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smart.refresh.layout.api.RefreshKernel com.scwang.smart.refresh.layout.api.RefreshKernel.onAutoRefreshAnimationEnd(android.animation.Animator, boolean)' on a null object reference
                                                                                                    	at com.scwang.smart.refresh.header.MaterialHeader$1.onAnimationEnd(MaterialHeader.java:397)
                                                                                                    	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
                                                                                                    	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:719)
                                                                                                    	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(Unknown Source:4)
                                                                                                    	at android.animation.Animator.callOnList(Animator.java:677)
                                                                                                    	at android.animation.Animator.notifyListeners(Animator.java:616)
                                                                                                    	at android.animation.Animator.notifyEndListeners(Animator.java:641)
                                                                                                    	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
                                                                                                    	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1585)
                                                                                                    	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
                                                                                                    	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
                                                                                                    	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1542)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:984)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by stevenwsg** [comment]
2.1.0， 2.1.1都会空指针， 回退到 2.0.5没问题
