### ISSUE TITLE
上拉加载更多异常 

### ISSUE THREAD

**Issue by 1762588562** [scwang90/SmartRefreshLayout#175]
布局文件为
<?xml version="1.0" encoding="utf-8"?>
<com.scwang.smartrefresh.layout.SmartRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/refresh_untreated_ticket"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.scwang.smartrefresh.layout.header.ClassicsHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <ListView
        android:id="@+id/lv_untreated_ticket"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:divider="@null"
        android:visibility="gone"></ListView>
    <com.scwang.smartrefresh.layout.footer.ClassicsFooter
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>

调用上拉获取更多报异常，异常信息如下：
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/widget/ListViewCompat;
                                                       at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper$4.onAnimationUpdate(RefreshContentWrapper.java:359)
                                                       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
                                                       at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384)
                                                       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427)
                                                       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759)
                                                       at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.widget.ListViewCompat" on path: DexPathList[[zip file "/data/app/com.yeepay.hbird-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yeepay.hbird-1/lib/arm64, /data/app/com.yeepay.hbird-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper$4.onAnimationUpdate(RefreshContentWrapper.java:359) 
                                                       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463) 
                                                       at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384) 
                                                       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427) 
                                                       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759) 
                                                       at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801) 
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) 
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                       at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                   	Suppressed: java.lang.ClassNotFoundException: android.support.v4.widget.ListViewCompat
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by scwang90** [comment]
更新你的支持包

**Comment by 1762588562** [comment]
请问更新哪个支持包？

**Comment by 1762588562** [comment]
你们对这两个包的最低要求版本是多少呢？以下是我引入的support包的版本
compile 'com.android.support:support-v4:22.2.2'
compile 'com.android.support:design:22.2.1'

**Comment by scwang90** [comment]
23 以上
