### ISSUE TITLE
apk的实战里面 微博按钮点击崩溃,原因如下,建议修改

### ISSUE THREAD

**Issue by Simonhy** [scwang90/SmartRefreshLayout#20]
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector

     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_feed_list_mail.xml from drawable resource ID #0x7f020062

**Comment by scwang90** [comment]
请问你使用的 安卓系统版本是？我好处理

**Comment by Simonhy** [comment]
我用的夜神模拟器 4.4版本出现的

**Comment by huclengyue** [comment]
@Simonhy @scwang90 将这几个布局里的 drawable的vector类型的图标换成普通的png就可以了

**Comment by Simonhy** [comment]
难道用不了svg类型的图片@scwang90

**Comment by huclengyue** [comment]
可能你的版本低吧 @Simonhy 我是4.4

**Comment by scwang90** [comment]
问题已经解决，重新下砸 Demo 即可
