### ISSUE TITLE
REFRESH_HEADER_LASTTIME 我把这个设置成英文 会报错

### ISSUE THREAD

**Issue by ynpl** [scwang90/SmartRefreshLayout#248]
我在 Application类中设置REFRESH_HEADER_LASTTIME 这个属性  设置成
 ClassicsHeader.REFRESH_HEADER_LASTTIME = "Last update  M-d HH:mm";
会报错 不知道为什么 别的属性设置成英文没有错误 只有这个属性 设置成英文之后就会报错 

错误信息  如下:
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.spelist.spelist/com.spelist.spelist.ui.activity.ProActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                    Caused by: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader
                                                                    Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class com.scwang.smartrefresh.layout.header.ClassicsHeader

**Comment by scwang90** [comment]
英文的话  M-d HH:mm 就够了，不需要别的了
