### ISSUE TITLE
页面初始化出现异常

### ISSUE THREAD

**Issue by onion90** [scwang90/SmartRefreshLayout#266]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.onion.netmvpdemo, PID: 23173
                                                                      java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.scwang.smartrefresh.layout.SmartRefreshLayout$LayoutParams
                                                                          at com.scwang.smartrefresh.layout.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:628)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1489)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1489)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1489)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1489)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
                                                                          at android.view.View.measure(View.java:19937)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2442)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1488)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1747)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:742)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:674)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
                                                                          at android.os.Handler.handleCallback(Handler.java:761)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:156)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

- [ ] 

- # 1.

**Comment by scwang90** [comment]
用 SmartRefreshLayout.LayoutParams 就好了
