### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1

### ISSUE THREAD

**Issue by DonaldDu** [scwang90/SmartRefreshLayout#272]
SmartRefreshLayout:1.0.4，因为是友盟统计结果，所以暂无复现方法。

java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
	at java.util.ArrayList.get(ArrayList.java:313)
	at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
	at android.widget.ListView.dispatchDraw(ListView.java:3453)
	at android.view.View.draw(View.java:16688)
	at android.widget.AbsListView.draw(AbsListView.java:4749)
	at android.view.View.updateDisplayListIfDirty(View.java:15622)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:759)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16688)
	at android.view.View.updateDisplayListIfDirty(View.java:15622)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1367)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.draw(View.java:16688)
	at android.view.View.updateDisplayListIfDirty(View.java:15622)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15614)
	at android.view.View.draw(View.java:16430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2794)
	at android.view.View.draw(View.java:16688)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2780)
	at android.view.View.updateDisplayListIfDirty(View.java:15622)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3091)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2895)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2507)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1338)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6872)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:899)
	at android.view.Choreographer.doCallbacks(Choreographer.java:701)
	at android.view.Choreographer.doFrame(Choreographer.java:636)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:885)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by scwang90** [comment]
这个错误 和 本库没有关系的

**Comment by yandeqing** [comment]
同问,用了这个库才闪退的,概率很大,希望能查下
