### ISSUE TITLE
NullPointer Exception caused by viewHolder.shouldignore when layout

### ISSUE THREAD

**Issue by Whoisurdady** [scwang90/SmartRefreshLayout#275]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
       at android.support.v7.widget.RecyclerView.findMinMaxChildLayoutPositions(RecyclerView.java:3757)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3494)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:232)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:664)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:795)
       at android.view.View.layout(View.java:17693)
       at android.view.ViewGroup.layout(ViewGroup.java:5739)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2350)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2072)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6467)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:908)
       at android.view.Choreographer.doCallbacks(Choreographer.java:720)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:894)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6209)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

碰到了这个空指针的bug，线上日志抓到的，目前无法确定复现的操作，不过概率还挺高的，希望可以修复或者说明一下怎么解决

**Comment by scwang90** [comment]
这样的错误一般和你使用的 Adapter相关，需要自行检查 ，看错误描述是 Adapter 返回给 RV 的 viewHolder 是 null 导致的
