### ISSUE TITLE
连网成功后偶尔出现空指针。大佬看看是我执行顺序不对吗，用的BaseRecyclerViewAdapterHelper

### ISSUE THREAD

**Issue by etenel** [scwang90/SmartRefreshLayout#276]
java.lang.NullPointerException: Attempt to invoke virtual method 'com.scwang.smartrefresh.layout.SmartRefreshLayout com.scwang.smartrefresh.layout.SmartRefreshLayout.finishRefresh()' on a null object reference
	at com.qianyuan.huojiaying.pager.property_pager.repair_service.HistoryReport$4.onSuccess(HistoryReport.java:172)
	at com.qianyuan.huojiaying.pager.property_pager.repair_service.HistoryReport$4.onSuccess(HistoryReport.java:160)
	at com.qianyuan.huojiaying.utils.httputils.HttpCallBack$2.run(HttpCallBack.java:63)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6166)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

这个是执行顺序
 adapter = new HIstoryReportAdapter(R.layout.item_history_report, datas);
        rlCase.setAdapter(adapter);
        initListener();
        getDataFromNet();
        refresh.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh(final RefreshLayout refreshlayout) {
                getDataFromNet();
                pager = 1;
            }
        });
        refresh.setOnLoadmoreListener(new OnLoadmoreListener() {
            @Override
            public void onLoadmore(final RefreshLayout refreshlayout) {
                loadMore();
            }
        });
    }
这是第一次进入的数据
  List<HistoryReportBean.DATABean> data = result.getDATA();
                        adapter.setNewData(data);
                        refresh.finishRefresh();
                        refresh.setLoadmoreFinished(false);

**Comment by scwang90** [comment]
这个空指针与 Smart 无关，你需要自己检查你的代码
