### ISSUE TITLE
在studio 3.0中 报： attribute 'packageName : srlDrawableArrowSize' not found.

### ISSUE THREAD

**Issue by lxfeng** [scwang90/SmartRefreshLayout#297]
gradle 版本 3.0.0-rc2

Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
	at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:454)
	at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:411)
	at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
	at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)

**Comment by scwang90** [comment]
这个和你使用的代码有关，我无能为力的

**Comment by Aaronzhou** [comment]
我也碰到同样的问题。。。这是什么情况
