### ISSUE TITLE
NullPointerException after upgrading from 1.0.3 to 1.0.4-4 when pulling down to refresh

### ISSUE THREAD

**Issue by flocsy** [scwang90/SmartRefreshLayout#299]
After I upgraded from 1.0.3 to 1.0.4-4 I get the following exception every time I pull down the screen to refresh:

```
   java.lang.NullPointerException: Attempt to invoke virtual method 'int com.scwang.smartrefresh.layout.constant.SpinnerStyle.ordinal()' on a null object reference
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.moveSpinner(SmartRefreshLayout.java:1513)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.moveSpinnerInfinitely(SmartRefreshLayout.java:1437)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:960)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
       at android.view.View.dispatchPointerEvent(View.java:10243)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6321)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6373)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
12-21 05:53:50.134 30385-30385/com.chegg E/AndroidRuntime:
       at android.view.Choreographer.doFrame(Choreographer.java:615)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by scwang90** [comment]
What Header do you use?

**Comment by flocsy** [comment]
Ok that worked, I chose Translate (randomly) because I couldn't really understand their meening via google translate :(
