### ISSUE TITLE
混淆异常

### ISSUE THREAD

**Issue by YougaKing** [scwang90/SmartRefreshLayout#301]
![image](https://user-images.githubusercontent.com/16010591/34332408-41e07390-e96b-11e7-839d-3b79ede6702c.png)
 java.lang.AbstractMethodError: abstract method "void android.view.View$OnScrollChangeListener.onScrollChange(android.view.View, int, int, int, int)"
                                                                    at android.view.View.onScrollChanged(View.java:11647)
                                                                    at android.support.v7.widget.RecyclerView.b(SourceFile:3924)
                                                                    at android.support.v7.widget.RecyclerView.v(SourceFile:47090)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3265)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at com.scwang.smartrefresh.layout.e.a.a(SourceFile:232)
                                                                    at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SourceFile:664)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.support.v4.view.ViewPager.onLayout(SourceFile:1695)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
12-25 11:59:58.366 1708-1708/com.dailyyoga.cn E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                                                    at android.view.View.layout(View.java:17637)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by scwang90** [comment]
这个异常和 smart 没有关系
