### ISSUE TITLE
加载更多出错

### ISSUE THREAD

**Issue by lastcrazydog** [scwang90/SmartRefreshLayout#319]
异常信息：
 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{4b247250 position=27 id=-1, oldPos=9, pLpos:9 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{4ab7bf34 VFED.... .F....I. 0,0-720,1152 #7f09016e app:id/rv}, adapter:com.capsa.dssp.mapservice.activity.poifavorite.PoiFavoriteAdapter@4afb7f48, layout:android.support.v7.widget.LinearLayoutManager@4b073484, context:com.capsa.dssp.mapservice.activity.poifavorite.PoiFavoriteActivity@4abff64c
                                                                  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5421)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5603)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:206)
                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:690)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                  at android.view.View.layout(View.java:14817)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2011)
                                                              	at android.view.ViewRootImpl.performTraversals(View

Adapter使用方法：
notifyItemRangeInserted(index, data.size());

**Comment by scwang90** [comment]
这个错误和 smart 无关
