### ISSUE TITLE
divide by zero when footer height set to 0

### ISSUE THREAD

**Issue by flocsy** [scwang90/SmartRefreshLayout#333]
If you use either of the following to set height to 0 then you'll get a division by 0 error if you move move the refreshlayout up (from the code it looks similar if I would set the header's height to 0):

        setRefreshFooter(new FalsifyFooter(context), 0, 0);
        setFooterHeightPx(0);

```
E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.example, PID: 20318
   java.lang.ArithmeticException: divide by zero
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.animSpinnerBounce(SmartRefreshLayout.java:1339)
       at com.scwang.smartrefresh.layout.SmartRefreshLayout.computeScroll(SmartRefreshLayout.java:785)
       at android.view.View.updateDisplayListIfDirty(View.java:18052)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
       at android.view.View.updateDisplayListIfDirty(View.java:18028)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by scwang90** [comment]
you can use
~~~java
    refreshLayout.setEnableRefresh(false);
    refreshLayout.setEnableOverScrollDrag(false);
~~~
replace
~~~java
    setRefreshFooter(new FalsifyFooter(context), 0, 0);
    setFooterHeightPx(0);
~~~
