### ISSUE TITLE
遇到一个新BUG

### ISSUE THREAD

**Issue by 957919019** [scwang90/SmartRefreshLayout#348]
![qq 20180118141939](https://user-images.githubusercontent.com/19183142/35083540-b3a36508-fc5a-11e7-9f1d-41ecad7a1822.png)
图片是我布局的结构，用这种结构配合https://github.com/bingoogolapple/BGASwipeBackLayout-Android
，在点击布局中任意的item跳转后，滑动返回的时候会报错：
java.lang.RuntimeException: PureScrollMode模式只支持一个子View，Most only support one sub view in PureScrollMode
                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate(SmartRefreshLayout.java:288)
                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.onAttachedToWindow(SmartRefreshLayout.java:372)
                                                                  at android.view.View.dispatchAttachedToWindow(View.java:...
但是我布局里确实只嵌套了一个容器，而项目里其他地方没有出现过这种问题，请问如何解决？

**Comment by scwang90** [comment]
这个问题已经修复了
