### ISSUE TITLE
阿里云兼容测试个别机型报ANR

### ISSUE THREAD

**Issue by snow888ak** [scwang90/SmartRefreshLayout#352]
机型：华为 Che1-CL10 4.4.4 720x1280 高通 骁龙 MSM8916
正面是ANR异常信息。
Input dispatching timed out (Waiting because the touched window has not finished processing the input events that were previously delivered to it.)
"main" prio=5 tid=1 SUSPENDED
  | group="main" sCount=1 dsCount=0 obj=0x4167cf18 self=0x415987a0
  | sysTid=17002 nice=0 sched=0/0 cgrp=apps handle=1074536788
  | state=S schedstat=( 7505486870 42113135955 14682 ) utm=629 stm=121 core=3
  at android.widget.TextView.onLayout(TextView.java:~6722)
  at android.view.View.layout(View.java:14884)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
  at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1686)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1462)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:8839)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1609)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at com.scwang.smartrefresh.layout.impl.RefreshContentWrapper.layout(RefreshContentWrapper.java:232)
  at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:664)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
  at android.view.View.layout(View.java:14884)
  at android.view.ViewGroup.layout(ViewGroup.java:4651)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2060)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1814)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1050)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5934)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
  at android.view.Choreographer.doCallbacks(Choreographer.java:600)
  at android.view.Choreographer.doFrame(Choreographer.java:569)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5336)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
  at dalvik.system.NativeStart.main(Native Method)

**Comment by scwang90** [comment]
这个错误和 smart 无关

**Comment by RuoYuHoney** [comment]
怎么解决的？？这个问题。定位到没
