### ISSUE TITLE
在8.0的手机上，淘宝二楼会boom。。

### ISSUE THREAD

**Issue by plmmanwu** [scwang90/SmartRefreshLayout#361]
如题

**Comment by scwang90** [comment]
需要提供详细信息

**Comment by plmmanwu** [comment]
01-24 23:26:59.266 21801-21801/? E/AndroidRuntime:     at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:84)
                                                       at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                       at com.scwang.smartrefresh.layout.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:579)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
01-24 23:26:59.266 21801-21801/? E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:830)
                                                       at android.view.View.measure(View.java:22216)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2568)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1628)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1512)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7218)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:721)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                       at android.os.Handler.dispatchMessage(Handler.java:101)
                                                       at android.os.Looper.loop(Looper.java:166)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7415)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by plmmanwu** [comment]
荣耀V9  android8.0

**Comment by plmmanwu** [comment]
1961  行爆红 提示RefreshInternal.onInitialized can only be called from subclasses

**Comment by scwang90** [comment]
新版 二级刷新Header 已经提交，
