### ISSUE TITLE
淘宝二楼在华为6.0的手机上会崩

### ISSUE THREAD

**Issue by zhuminjunivan** [scwang90/SmartRefreshLayout#362]
`01-25 09:49:44.074 25381-25381/com.scwang.refreshlayout.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.scwang.refreshlayout.app, PID: 25381
                                                                              java.lang.StackOverflowError: stack size 8MB
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                                  at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(TwoLevelHeader.java:188)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:1961)
                                                                                  at com.scwang.smartrefresh.layout.SmartRefreshLayout.setHeaderMaxDragRate(SmartRefreshLayout.java:83)
                                                                              	at com.scwang.refreshlayout.widget.TwoLevelHeader.onInitialized(Two`

     华为畅享6 android6.0 
     1.0.4-7

**Comment by zhuminjunivan** [comment]
应该是是层级调用过多 出错是在TwoLevelHeader里onInitialized方法  kernel.getRefreshLayout().setHeaderMaxDragRate(mMaxRage);

**Comment by scwang90** [comment]
新版 二楼Header已经提交
