### ISSUE TITLE
求教,这个bug是由什么引起的?

### ISSUE THREAD

**Issue by ka-lun-ren** [scwang90/SmartRefreshLayout#410]
小米市场的猴子发现的...不知道这个是由什么引起的,我知道可以改源码加个类型判断就可以了,但我不想改lib啊~
java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
at com.scwang.smartrefresh.layout.SmartRefreshLayout$3.run(SmartRefreshLayout.java:439)
at com.scwang.smartrefresh.layout.util.DelayedRunnable.run(DelayedRunnable.java:14)
at android.os.Handler.handleCallback(Handler.java:742)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5555)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by scwang90** [comment]
这个只是一个 smart 的log，新版中已经屏蔽了，现在也不会影响运行效果的，等稳定版出来换上就不会有了
