### ISSUE TITLE
阿里测试有个别机型出现Crash

### ISSUE THREAD

**Issue by lk4403** [scwang90/SmartRefreshLayout#432]
1. Crash: java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
共 4 次
java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
at com.scwang.smartrefresh.layout.SmartRefreshLayout$6.run(TbsSdkJava:439)
at com.scwang.smartrefresh.layout.e.a.run(TbsSdkJava:14)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4825)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
at dalvik.system.NativeStart.main(Native Method)

**Comment by scwang90** [comment]
这个只是 log，不会影响运行的，这个log 在新版本中已经去掉了
