### ISSUE TITLE
华为 H60-l03 Android版本 4.4.2报错 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by wyh497823256** [scwang90/SmartRefreshLayout#465]
SmartRefreshLayout 版本 1.0.5
机型：华为 H60-l03
Android版本 4.4.2
报错信息如下：
04-19 19:24:38.035 25831-25831/com.lingdong.xiaoqu E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.StackOverflowError
        at android.text.TextLine.measureRun(TextLine.java:414)
        at android.text.TextLine.measure(TextLine.java:293)
        at android.text.TextLine.metrics(TextLine.java:267)
        at android.text.Layout.getLineExtent(Layout.java:998)
        at android.text.Layout.drawText(Layout.java:329)
        at android.text.Layout.draw(Layout.java:205)
        at android.widget.TextView.onDraw(TextView.java:5259)
        at android.view.View.draw(View.java:14517)
        at android.view.View.getDisplayList(View.java:13401)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.draw(View.java:14520)
        at android.view.View.getDisplayList(View.java:13401)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4607)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.draw(View.java:14520)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4013)
        at android.view.View.getDisplayList(View.java:13401)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:717)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.draw(View.java:14520)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13401)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
        at android.view.View.draw(View.java:14234)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
        at android.view.View.getDisplayList(View.java:13396)
        at android.view.View.getDisplayList(View.java:13443)
    	at android.view.View.draw(View.java:

其他设备暂未发生此错误

**Comment by wyh497823256** [comment]
@scwang90 问题是我不使用smart 就不会报错啊！
at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:717)
