### ISSUE TITLE
SmartRefreshLayout中包含的listview含有自带header(listview.addheader)时,下拉刷新会出现数组越界异常

### ISSUE THREAD

**Issue by kimonic** [scwang90/SmartRefreshLayout#467]
快速上下拉时会出现数组越界异常,怀疑是刷新的时候清除了数据源数据,而越界回弹的刷新未完成导致的
版本1.0.4,1.1.0-alpha-1,均有这个问题
public class SmartActivity extends AppCompatActivity {
    private ListView lvFragDiscover;
    private SmartRefreshLayout srl;
    private List<String> list;
    private MAdapter adapter;

    /**加载布局文件*/
    public int getLayoutResId() {
        return R.layout.act_smart;
    }

  

   
    public void initView() {
        lvFragDiscover=findViewById(R.id.lv_frag_discover);
        srl=findViewById(R.id.srl_frag_discover);

        list=new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            list.add(""+i);
        }
        TextView view = new TextView(this);
        view.setText("header");
        lvFragDiscover.addHeaderView(view);

         adapter=new MAdapter(list, this);
        lvFragDiscover.setAdapter(adapter);

        srl.setPrimaryColors(Color.RED);
        srl.setRefreshHeader(new BezierRadarHeader(this));
        srl.setEnableLoadmore(false);
    }

    @Override
    public void initListener() {
        srl.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh(RefreshLayout refreshlayout) {
                list.clear();
                new Thread(){
                    @Override
                    public void run() {//模拟异步加载数据
                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                loadInternetDataToUi();

                            }
                        });

                    }
                }.start();
//                finishRL();
            }
        });
    }

   

    @Override
    public void loadInternetDataToUi() {
        List<String>  list1=new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            list1.add(""+i*2);
        }
        srl.finishRefresh();
        list.addAll(list1);
        adapter.notifyDataSetChanged();

    }

    private class MAdapter extends BaseAdapter {
        private List<String> list;
        private Context context;

        public MAdapter(List<String> list, Context context) {
            this.list = list;
            this.context = context;
        }

        @Override
        public int getCount() {
            return list.size();
        }

        @Override
        public Object getItem(int position) {
            return list.get(position);
        }

        @Override
        public long getItemId(int position) {
            return position;
        }

        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            View view;
            ViewHolder viewHolder;
            if (convertView == null) {
                viewHolder = new ViewHolder();
                view = new TextView(context);
                viewHolder.textView = (TextView) view;
                view.setTag(viewHolder);

            }else {
                view=convertView;
                viewHolder= (ViewHolder) view.getTag();
            }

            viewHolder.textView.setText(list.get(position));
            return view;
        }

        private class ViewHolder {
            TextView textView;
        }
    }

}
布局文件
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <com.scwang.smartrefresh.layout.SmartRefreshLayout
        android:id="@+id/srl_frag_discover"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        app:srlEnableHeaderTranslationContent="true"
        app:srlEnableLoadmore="false"
        app:srlEnableRefresh="true">

        <ListView
            android:id="@+id/lv_frag_discover"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="12dp"
            android:dividerHeight="10dp" />

    </com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>

报的异常
FATAL EXCEPTION: main
                                                                Process: com.kimonic.test, PID: 9015
                                                                java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                                    at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
                                                                    at android.widget.AbsListView.onTouchDown(AbsListView.java:3718)
                                                                    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3627)
                                                                    at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at com.scwang.smartrefresh.layout.SmartRefreshLayout.superDispatchTouchEvent(SmartRefreshLayout.java:1010)
                                                                    at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:899)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                    at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                    at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                    at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                    at android.os.Looper.loop(Looper.java:122)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                	at java.lang.reflect.Me

**Comment by scwang90** [comment]
这个问题和smart无关

**Comment by kimonic** [comment]
不含header的时候,刷新是正常的 ,只有添加了header才会崩溃

**Comment by yandeqing** [comment]
同问,可以确定100%和smart有关系

**Comment by gaoxuge** [comment]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.viewpager.widget.ViewPager.performDrag(ViewPager.java:2324)
	at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2242)
	at android.view.View.dispatchTouchEvent(View.java:14632)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3163)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:1091)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4272)
	at com.retech.common.base.BaseActivity.dispatchTouchEvent(BaseActivity.java:146)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14899)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6682)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6453)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6119)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6176)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8942)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8893)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8854)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9085)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:240)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9030)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9171)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1227)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1024)
	at android.view.Choreographer.doFrame(Choreographer.java:918)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1212)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Back traces ends.
