### ISSUE TITLE
崩溃错误 java.lang.NoSuchMethodError: No static method lambda$static$1

### ISSUE THREAD

**Issue by Wiolem** [scwang90/SmartRefreshLayout#49]
```
FATAL EXCEPTION: main
                                                                             Process: com.buglee.lee.timelinenote, PID: 15368
                                                                             Theme: themes:{default=overlay:com.zui.theme.XuiSkin.pink, iconPack:com.zui.theme.XuiSkin.pink}
                                                                             java.lang.NoSuchMethodError: No static method lambda$static$1(Landroid/content/Context;Lcom/scwang/smartrefresh/layout/api/RefreshLayout;)Lcom/scwang/smartrefresh/layout/api/RefreshHeader; in class Lcom/scwang/smartrefresh/layout/SmartRefreshLayout; 
                                                                                 at com.scwang.smartrefresh.layout.SmartRefreshLayout$$Lambda$15.createRefreshHeader(Unknown Source)
                                                                                 at com.scwang.smartrefresh.layout.SmartRefreshLayout.onAttachedToWindow(SmartRefreshLayout.java:383)
```

**Comment by scwang90** [comment]
这是混淆之后出现的吗

**Comment by Wiolem** [comment]
没有混淆，应该是我的项目问题，但我还是没找到原因

**Comment by scwang90** [comment]
demo项目你能运行成功吗

**Comment by Wiolem** [comment]
可以，就是在我的项目中不行，也没找到具体原因

**Comment by zhangrui49** [comment]
我也出现这个问题,我用的kotlin

**Comment by scwang90** [comment]
@Wiolem 你用的也是 kotlin 吗？

**Comment by Wiolem** [comment]
不是kotin

**Comment by scwang90** [comment]
问题已经解决，请更新版本到最新版本

**Comment by Wiolem** [comment]
@scwang90 OK了，完美添加，谢谢了
