### ISSUE TITLE
ClassCastException警告

### ISSUE THREAD

**Issue by HuangJAndroid** [scwang90/SmartRefreshLayout#510]
System.err: java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
        at com.scwang.smartrefresh.layout.SmartRefreshLayout$3.run(SmartRefreshLayout.java:439)
        at com.scwang.smartrefresh.layout.util.DelayedRunnable.run(DelayedRunnable.java:14)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by scwang90** [comment]
更新到最新版本就好了
