### ISSUE TITLE
设置paint颜色在paint初始化之前调用导致的NPE问题

### ISSUE THREAD

**Issue by MichaelArchangel** [scwang90/SmartRefreshLayout#518]
https://github.com/scwang90/SmartRefreshLayout/blob/02a66400b33e6a9ac8a060baef2a5e1d50056ecd/refresh-layout/src/main/java/com/scwang/smartrefresh/layout/footer/BallPulseFooter.java#L87

**Comment by scwang90** [comment]
没有发现 NPE 问题呢~

**Comment by MichaelArchangel** [comment]
@scwang90 我这里是报了这个错误...
`05-29 14:08:16.197 28073-28073/com.velotech.veereditor.evo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.velotech.veereditor.evo, PID: 28073
    android.view.InflateException: Binary XML file line #284: Binary XML file line #284: Error inflating class com.scwang.smartrefresh.layout.footer.BallPulseFooter
    Caused by: android.view.InflateException: Binary XML file line #284: Error inflating class com.scwang.smartrefresh.layout.footer.BallPulseFooter
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.velotech.veerlib.views.BaseFragment.onCreateView(BaseFragment.java:55)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference
        at com.scwang.smartrefresh.layout.footer.BallPulseFooter.setNormalColor(BallPulseFooter.java:223)
        at com.scwang.smartrefresh.layout.footer.BallPulseFooter.<init>(BallPulseFooter.java:74)
        at com.scwang.smartrefresh.layout.footer.BallPulseFooter.<init>(BallPulseFooter.java:62)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:651) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.velotech.veerlib.views.BaseFragment.onCreateView(BaseFragment.java:55) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) `

布局里是这样写的：
`<com.scwang.smartrefresh.layout.footer.BallPulseFooter
android:layout_width = "match_parent"
android:layout_height = "wrap_content"
app:srlAnimatingColor = "@color/blue_500"
app:srlNormalColor = "@color/blue_300"/>`

**Comment by MichaelArchangel** [comment]
@scwang90 setNormalColor的时候mIsStarted是false，所以尝试给mPaint设置颜色就NPE了...

**Comment by MichaelArchangel** [comment]
@scwang90 你那边不会复现吗？我这边写成这样一定会报错：
<com.scwang.smartrefresh.layout.footer.BallPulseFooter
			android:layout_width = "match_parent"
			android:layout_height = "wrap_content"
			app:srlNormalColor = "@color/blue"/>
