### ISSUE TITLE
onDetachedFromWindow

### ISSUE THREAD

**Issue by ltyhome** [scwang90/SmartRefreshLayout#519]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onDetachedFromWindow(SmartRefreshLayout.java)
	at android.view.View.dispatchDetachedFromWindow(View.java:14599)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3110)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3234)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:5900)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4129)
	at android.app.ActivityThread.access$1700(ActivityThread.java:170)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

OPPO R9,荣耀KNT-UL10,好多机型上出现这个问题，麻烦定位一下原因

**Comment by scwang90** [comment]
新版本已经解决这个问题
