### ISSUE TITLE
pointerIndex out of range 

### ISSUE THREAD

**Issue by will746** [scwang90/SmartRefreshLayout#532]
（Android 7.0 - M5 Note）
低概率，只统计到几次异常。

java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2125)
	at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2235)
	at android.view.View.dispatchTouchEvent(View.java:10128)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:950)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:437)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1841)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3099)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
	at android.view.View.dispatchPointerEvent(View.java:10359)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5032)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4865)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4498)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4555)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6947)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6921)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6864)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7128)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:191)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:182)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7078)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7154)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:921)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:652)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:907)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by scwang90** [comment]
你使用的 smart 和 ViewPager 支持包对应的版本分别是什么？

**Comment by will746** [comment]
compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0-alpha-5'
   compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-alpha-6'
   Viewpager支持包？
  android.support.v4.view.ViewPager

**Comment by will746** [comment]
你指的是这个吗？
implementation 'com.android.support:appcompat-v7:26.1.0'
implementation 'com.android.support:design:26.1.0'

**Comment by aeatho** [comment]
> 你指的是这个吗？
> implementation 'com.android.support:appcompat-v7:26.1.0'
> implementation 'com.android.support:design:26.1.0'

这个bug是怎么造成的啊？？？

**Comment by will746** [comment]
> > 你指的是这个吗？
> > 实行'com.android.support:appcompat-v7:26.1.0' 
> > 执行'com.android.support:design:26.1.0'
> 
> 这个错误是怎么造成的啊???

页面自动刷新在刚加载的时候快速滑动的时候出现的，异常统计也统计过几次

**Comment by amd110** [comment]
我也统计到了几次这个异常

**Comment by scwang90** [comment]
老版本解决此问题：把列表缓存 RecyclerView 或者 NestScrollView ，并开启 Smart 的嵌套滚动功能
新版本解决此问题：把列表缓存 RecyclerView 或者 NestScrollView ，直接使用 1.1.0 系列最新版本

**Comment by Dammyouh** [comment]
老版本解决此问题：把列表换成 RecyclerView 或者 NestScrollView ，并开启 Smart 的嵌套滚动功能
新版本解决此问题：把列表换成 RecyclerView 或者 NestScrollView ，直接使用 1.1.0 系列最新版本
————————————————————————————————————————
使用的是1.1.0，smartLayout中CoordinatorLayout，然后有viewPager,viewPager中的Fragment中用的RecyclerView。还是报上面的问题 pointerIndex out of range  欧

**Comment by Dammyouh** [comment]
这个应该是viewpager的问题，需要重写viewPager. https://blog.csdn.net/nnmmbb/article/details/28419779

class MultiPointerViewPager @JvmOverloads constructor(context: Context, attr: AttributeSet? = null)
    : ViewPager(context, attr) {

    private val tag = MultiPointerViewPager::class.java.simpleName


    @SuppressLint("ClickableViewAccessibility")
    override fun onTouchEvent(ev: MotionEvent?): Boolean {
        try {
            return super.onTouchEvent(ev)
        } catch (ex: Exception) {
            Log.d(tag, "MultiPointerViewPager  onTouchEvent 抛出异常 $ex")
        }
        return false
    }

    override fun onInterceptTouchEvent(ev: MotionEvent?): Boolean {
        try {
            return super.onInterceptTouchEvent(ev)
        } catch (ex: Exception) {
            Log.d(tag, "MultiPointerViewPager  onInterceptTouchEvent 抛出异常 $ex")
        }
        return false
    }
}

**Comment by lkkz** [comment]
我的ViewPage中onTouchEvent和onInterceptTouchEvent方法都返回的false，理论上不会抛Exception,但是依然会有这个异常，如下解决可以吧
class SafeSmartRefreshLayout : SmartRefreshLayout {

    constructor(context: Context):this(context,null)

    constructor(context: Context,attrs: AttributeSet?):super(context, attrs)

    /**
     * java.lang.IllegalArgumentException: pointerIndex out of range
     * at android.view.MotionEvent.nativeGetAxisValue(Native Method)
     */
    override fun dispatchTouchEvent(e: MotionEvent?): Boolean {
        return try {
            super.dispatchTouchEvent(e)
        }catch (ignore:Exception){
            false
        }
    }
}
