### ISSUE TITLE
java.lang.IllegalStateException  ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)

### ISSUE THREAD

**Issue by banxi1988** [scwang90/SmartRefreshLayout#533]
看到报错的堆栈中有 smartrefresh 的身影，不知道有没有关系。
我检查我使用 createViewHolder 的代码， layout 时没有 attached 的地方。

```

1 android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source)
--
2 android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source)
3 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
4 android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source)
5 android.support.v7.widget.LinearLayoutManager$LayoutState.next(Unknown Source)
6 android.support.v7.widget.LinearLayoutManager.layoutChunk(Unknown Source)
7 android.support.v7.widget.LinearLayoutManager.fill(Unknown Source)
8 android.support.v7.widget.LinearLayoutManager.onLayoutChildren(Unknown Source)
9 android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source)
10 android.support.v7.widget.RecyclerView.dispatchLayout(Unknown Source)
11 android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
12 android.view.View.layout(View.java:17993)
13 android.view.ViewGroup.layout(ViewGroup.java:5817)
14 com.scwang.smartrefresh.layout.c.a.a(Unknown Source)
15 com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(Unknown Source)
16 android.view.View.layout(View.java:17993)
17 android.view.ViewGroup.layout(ViewGroup.java:5817)
18 android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
19 android.widget.FrameLayout.onLayout(FrameLayout.java:281)


```

**Comment by banxi1988** [comment]
看到隔壁有一个库也有人报类似的问题：
https://github.com/ShamylZakariya/StickyHeaders/issues/87

**Comment by scsfwgy** [comment]
@scwang90 

compileSdkVersion 27
minSdkVersion 16
targetSdkVersion 25

`1902-14 18:07:09.337 2664 2664 E AndroidRuntime: at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:655)`


`

02-14 18:07:09.337 2664 2664 E AndroidRuntime: FATAL EXCEPTION: main
--
102-14 18:07:09.337 2664 2664 E AndroidRuntime: Process: com.tophold.xcfd, PID: 2664
202-14 18:07:09.337 2664 2664 E AndroidRuntime: java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
702-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
802-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
902-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
1002-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
1102-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
1202-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
1302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
1402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
1502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
1602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
1702-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
1802-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
1902-14 18:07:09.337 2664 2664 E AndroidRuntime: at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:655)
2002-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
2102-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
2202-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
2302-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.View.layout(View.java:19828)
2402-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6154)
2502-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
2602-14 18:07:09.337 2664 2664 E AndroidRuntime: at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

`

**Comment by XiaLeon** [comment]
@banxi1988 这个问题你解决了吗？我也遇到了
