### ISSUE TITLE
TwoLevelHeader 崩溃

### ISSUE THREAD

**Issue by zeyaosu** [scwang90/SmartRefreshLayout#541]
淘宝二楼崩溃，我看1月25号说的新版header已解决，现在好像还是崩溃，Android版本7.0

06-07 18:07:43.428 9518-9518/test.myapplication E/AndroidRuntime:     at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)
        at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)
        at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)
        at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)
        at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)
        at com.scwang.smartrefresh.layout.header.TwoLevelHeader.onInitialized(TwoLevelHeader.java:198)
        at com.scwang.smartrefresh.layout.internal.InternalAbstract.onInitialized(InternalAbstract.java:89)

**Comment by scwang90** [comment]
新版已发布 1.1.0-7
