### ISSUE TITLE
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{43a783c0 position=0 id=-1, oldPos=-1, pLpos:-1}

### ISSUE THREAD

**Issue by hudan2714** [scwang90/SmartRefreshLayout#595]
.SmartRefreshLayout.onLayout(TbsSdkJava:667)

at android.support.v7.widget.RecyclerView$5.attachViewToParent(TbsSdkJava:763)
	at android.support.v7.widget.ChildHelper.attachViewToParent(TbsSdkJava:239)
	at android.support.v7.widget.RecyclerView.addAnimatingView(TbsSdkJava:1274)
	at android.support.v7.widget.RecyclerView.animateChange(TbsSdkJava:3831)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(TbsSdkJava:3643)
	at android.support.v7.widget.RecyclerView.dispatchLayout(TbsSdkJava:3323)
	at android.support.v7.widget.RecyclerView.onLayout(TbsSdkJava:3844)
	at android.view.View.layout(View.java:14889)
	at android.view.ViewGroup.layout(ViewGroup.java:4651)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14889)
	at android.view.ViewGroup.layout(ViewGroup.java:4651)

**Comment by scwang90** [comment]
这个错误和 smart 没关系

**Comment by MichaelJokAr** [comment]
same error

```
    at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:684)
```

```
 at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:842)
        at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
        at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1355)
        at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:4069)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3872)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:684)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20672)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
```

**Comment by AndSync** [comment]
解决了吗？@MichaelJokAr  @hudan2714我也遇到了
