### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: 

### ISSUE THREAD

**Issue by kong-jing** [scwang90/SmartRefreshLayout#606]
上拉加载的时候报这个问题。
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
        at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
        at android.support.v7.widget.DefaultItemAnimator.animateAdd(DefaultItemAnimator.java:218)
        at android.support.v7.widget.SimpleItemAnimator.animateAppearance(SimpleItemAnimator.java:114)
        at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3804)
        at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:521)
        at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:247)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:665)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15806)
        at android.view.ViewGroup.layout(ViewGroup.java:5038)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:581)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:516)
    	at android.view.View.layout(
```

**Comment by kong-jing** [comment]
出现android/support/v4/中找不到类或者方法，可以确定是依赖了多个不同版本的support库
