### ISSUE TITLE
RefreshHeader.getView() 报空指针

### ISSUE THREAD

**Issue by yinhe-zeng** [scwang90/SmartRefreshLayout#613]
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View com.scwang.smartrefresh.layout.api.RefreshHeader.getView()' on a null object reference

 at com.scwang.smartrefresh.layout.SmartRefreshLayout.onAttachedToWindow(SmartRefreshLayout.java:439)
        at android.view.View.dispatchAttachedToWindow(View.java:14624)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2845)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1396)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6238)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by scwang90** [comment]
getView 是自己控制的

**Comment by yinhe-zeng** [comment]
没有自定义Header，用的是默认的Header

**Comment by scwang90** [comment]
全局 DefaultRefreshHeaderCreator 中不要返回 null
