### ISSUE TITLE
关于使用特殊Header的问题

### ISSUE THREAD

**Issue by steven945** [scwang90/SmartRefreshLayout#654]
我使用了特殊header，加入<com.scwang.smartrefresh.header.DropboxHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
在下拉时候直接报错java.lang.AbstractMethodError: abstract method "void com.scwang.smartrefresh.layout.api.RefreshInternal.onPulling(float, int, int, int)"
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.moveSpinner(SmartRefreshLayout.java:1623)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.moveSpinnerInfinitely(SmartRefreshLayout.java:1528)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:1036)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)

**Comment by scwang90** [comment]
header 和 refresh 的版本必须一致
