### ISSUE TITLE
com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:623)

### ISSUE THREAD

**Issue by hulixia1992** [scwang90/SmartRefreshLayout#768]
设备信息:android 7.1.1 (25)，vivo:vivo Y75:arm64-v8a
错误日志:
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4692)
	at android.view.ViewGroup.addView(ViewGroup.java:4525)
	at android.view.ViewGroup.addView(ViewGroup.java:4465)
	at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:778)
	at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8222)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8180)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8168)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1573)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:623)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:882)
	at android.view.View.layout(View.java:17989)
	at android.view.ViewGroup.layout(ViewGroup.java:5872)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2732)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7031)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:942)
	at android.view.Choreographer.doCallbacks(Choreographer.java:744)
	at android.view.Choreographer.doFrame(Choreographer.java:676)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:928)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6482)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1098)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:959)

**Comment by scwang90** [comment]
过了这么久，应该自己解决了吧
