### ISSUE TITLE
实战，weibo 主页点击异常。

### ISSUE THREAD

**Issue by yihu5566** [scwang90/SmartRefreshLayout#80]
Process: com.scwang.refreshlayout, PID: 21970
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scwang.refreshlayout/com.scwang.refreshlayout.activity.practice.WeiboPracticeActivity}: java.lang.ClassCastException: android.widget.ScrollView cannot be cast to android.support.v4.widget.NestedScrollView
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7407)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                           Caused by: java.lang.ClassCastException: android.widget.ScrollView cannot be cast to android.support.v4.widget.NestedScrollView
                                                                              at com.scwang.refreshlayout.activity.practice.WeiboPracticeActivity.onCreate(WeiboPracticeActivity.java:44)
                                                                              at android.app.Activity.performCreate(Activity.java:6904)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7407) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by scwang90** [comment]
收到，谢谢

**Comment by scwang90** [comment]
问题已修复，重新下载即可

**Comment by yihu5566** [comment]
辛苦了
