### ISSUE TITLE
删除单条，重新刷新数据之后会报错

### ISSUE THREAD

**Issue by akumaCN** [scwang90/SmartRefreshLayout#893]
错误：
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{fa27386 position=6 id=-1, oldPos=6, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{91b3fa4 VFED.V... ......I. 0,0-720,1012 #7f0902e0 app:id/recycler_view}, adapter:com.xxx.adapter.recycleview.FixedVehiclesAdapter@933e83e, layout:androidx.recyclerview.widget.LinearLayoutManager@9d0f69f, context:com.xxx.FixedVehiclesActivity@3ec5fbb
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5859)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6042)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6002)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5998)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3984)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3748)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4303)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:691)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:888)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2674)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2377)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by akumaCN** [comment]
我的adapter删除方法
 if (mData.size() > pos) {
            mData.remove(pos);
            notifyItemRangeChanged(pos, mData.size());
        }
不是很明白，为什么我notifyItemRangeChanged过后，SmartRefreshLayout依然会报 Inconsistency detected.

**Comment by jklwan** [comment]
需要调用删除
> if (mData.size() > pos) {
>       mData.remove(pos);
>       notifyItemRemoved(pos);
>       notifyItemRangeChanged(pos, mData.size());
> }

**Comment by 18297793087** [comment]
notifyDataSetChanged

**Comment by 18297793087** [comment]
notifyDataSetChanged/notifyItemRangeRemoved
