### ISSUE TITLE
最近在Android P上遇到java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of，请作者大大做下Android P的兼容 

### ISSUE THREAD

**Issue by a9151357635** [scwang90/SmartRefreshLayout#929]
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
    at android.support.v7.widget.RecyclerView$a.createViewHolder(Unknown Source:27)
    at android.support.v7.widget.RecyclerView$n.a(Unknown Source:291)
    at android.support.v7.widget.RecyclerView$n.b(Unknown Source:5)
    at android.support.v7.widget.RecyclerView$n.d(Unknown Source:1)
    at android.support.v7.widget.LinearLayoutManager$c.a(Unknown Source:11)
    at android.support.v7.widget.LinearLayoutManager.a(Unknown Source:0)
    at android.support.v7.widget.LinearLayoutManager.a(Unknown Source:38)
    at android.support.v7.widget.LinearLayoutManager.e(Unknown Source:334)
    at android.support.v7.widget.RecyclerView.B(Unknown Source:38)
    at android.support.v7.widget.RecyclerView.c(Unknown Source:37)
    at android.support.v7.widget.RecyclerView.onLayout(Unknown Source:5)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at com.scwang.smartrefresh.layout.d.c.a(Unknown Source:2)
    at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(Unknown Source:103)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.support.v7.widget.ActionBarOverlayLayout.onLayout(Unknown Source:55)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
    at android.view.View.layout(View.java:20699)
    at android.view.ViewGroup.layout(ViewGroup.java:6198)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2840)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
    at android.view.Choreographer.doCallbacks(Choreographer.java:888)
    at android.view.Choreographer.doFrame(Choreographer.java:819)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6810)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by a9151357635** [comment]
版本升级就好了
