### ISSUE TITLE
com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:684)

### ISSUE THREAD

**Issue by xiaosalanqiao** [scwang90/SmartRefreshLayout#936]
请问这个问题要如何解决？错误信息如下：

java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:684)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1644)
	at android.support.v7.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1498)
	at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at me.yokeyword.fragmentation.SwipeBackLayout.onLayout(SwipeBackLayout.java:300)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2840)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by kmlixh** [comment]
这个是你写RecyclerView写的有问题吧

**Comment by scwang90** [comment]
自行百度
