### ISSUE TITLE
偶遇空指针，可惜忘记了操作流程

### ISSUE THREAD

**Issue by tianshaokai** [scwang90/SmartRefreshLayout#997]
2019-08-09 17:56:24.729 16141-16141/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scwang.refreshlayout.app, PID: 16141
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.util.SparseArray.put(int, java.lang.Object)' on a null object reference
        at android.support.v4.app.FragmentManagerImpl.makeInactive(FragmentManager.java:1906)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1601)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:631)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:612)
        at com.scwang.refreshlayout.activity.IndexMainActivity.onNavigationItemSelected(IndexMainActivity.java:104)
        at android.support.design.widget.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:204)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.design.internal.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
        at android.view.View.performClick(View.java:5780)
        at android.view.View$PerformClick.run(View.java:23120)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6910)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2019-08-09 17:56:24.870 1266-1454/? E/InputDispatcher: channel 'e0ed819 com.scwang.refreshlayout.app/com.scwang.refreshlayout.activity.style.DropBoxStyleActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by scwang90** [comment]
thanks

**Comment by tianshaokai** [comment]
(this:0x74f443e800,id:254,api:1,p:-1,c:374) ged queue fail: hnd:0x74fae718e0 api:1 pid:-1 size:1lu
2019-08-13 10:09:02.944 374-374/? E/BufferQueueProducer: [com.scwang.refreshlayout.app/com.scwang.refreshlayout.activity.IndexMainActivity](this:0x74f443d000,id:257,api:1,p:-1,c:374) ged queue fail: hnd:0x74faef6900 api:1 pid:-1 size:1lu
2019-08-13 10:09:03.216 7701-7701/? E/InputEventReceiver: Exception dispatching input event.
2019-08-13 10:09:03.218 7701-7701/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scwang.refreshlayout.app, PID: 7701
    java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewGroup com.scwang.smartrefresh.layout.api.RefreshLayout.getLayout()' on a null object reference
        at com.scwang.refreshlayout.fragment.practice.SecondFloorPracticeFragment$2.onHeaderMoving(SecondFloorPracticeFragment.java:71)
        at com.scwang.smartrefresh.layout.listener.SimpleMultiPurposeListener.onHeaderMoving(SimpleMultiPurposeListener.java:33)
        at com.scwang.smartrefresh.layout.listener.SimpleMultiPurposeListener.onHeaderMoving(SimpleMultiPurposeListener.java:110)
        at com.scwang.smart.refresh.layout.SmartRefreshLayout$RefreshKernelImpl.moveSpinner(SmartRefreshLayout.java:3625)
        at com.scwang.smart.refresh.layout.SmartRefreshLayout.moveSpinnerInfinitely(SmartRefreshLayout.java:1654)
        at com.scwang.smart.refresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:999)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2775)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:511)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1869)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:461)
        at android.view.View.dispatchPointerEvent(View.java:10494)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5441)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5239)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4696)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4756)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4715)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4884)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4723)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4941)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4696)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4756)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4715)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4723)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4696)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7418)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7392)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7335)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7590)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
2019-08-13 10:09:03.219 7701-7701/? E/AndroidRuntime:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7549)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7616)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:916)
        at android.view.Choreographer.doCallbacks(Choreographer.java:718)
        at android.view.Choreographer.doFrame(Choreographer.java:644)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:902)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6910)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2019-08-13 10:09:03.398 1349-1460/? E/InputDispatcher: channel '83ff668 com.scwang.refreshlayout.app/com.scwang.refreshlayout.activity.FragmentActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-08-13 10:09:03.468 1349-1460/? E/InputDispatcher: channel '7a58ac0 com.scwang.refreshlayout.app/com.scwang.refreshlayout.activity.IndexMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-08-13 10:09:03.473 1349-1487/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=44, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
2019-08-13 10:09:03.898 8007-8026/? E/ActivityThread: Failed to find provider info for cn.teddymobile.free.anteater.den.provider
2019-08-13 10:09:04.380 8007-8007/? E/BufferQueueProducer: [ScreenshotClient](this:0xd11ecc00,id:0,api:1,p:-1,c:8007) ged queue fail: hnd:0xed7ffc00 api:1 pid:-1 size:1llu
2019-08-13 10:09:05.101 8093-8112/? E/SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=PERSIST] 
2019-08-13 10:09:05.148 1349-3622/? E/LocationManagerService: fakeLocationFeatureEnable result =  false
2019-08-13 10:09:05.172 8093-8107/? E/CellLocation: create CdmaCellLocation

**Comment by tianshaokai** [comment]
@scwang90  点击SecondFloor 页面后，往下滑动页面 就会出现
